[package]
name = "near-seed-phrase"
version = "1.0.0"
edition = "2021"
description = "NEAR Seed Phrase"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bip39 = "2.2.0"
ed25519-dalek = "2.2.0"
thiserror = "2.0.0"
slipped10 = "0.4.0"
bs58 = "0.5.0"
rand = "0.8.0"

[features]
rand = [
    "bip39/rand",
    "ed25519-dalek/rand_core"
]
